### ISSUE TITLE
OOM issue

### ISSUE THREAD

**Issue by HanchengDeng** [lovecambi/qebrain#16]
Hi，I‘m using 4 2080Ti GPUs to train the Bilingual Expert， but the system always tells me that "tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[2048,120001] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [[{{node gradients/AddN/tmp_var}}]]".
I thought that was the problem caused by too big batch_size, but I changed the batch_size to 64. and the OOM problem still existed. 
Can you tell me is that some other parameter I need change to make the programs work? Or  4 2080Ti GPUs is not powerful enough to make it?

**Comment by lovecambi** [comment]
You probably need to use the BPE tokens rather than words. If using BPE tokens, I think it is fine for sentence level prediction, but for word level prediction, you may need to modify the code or the prepared data. For example, you can follow the sequence labeling method in BERT fine-tuning, which is just to predict the label of the first BPE token for each word. Alternatively, you can label each BPE token of the word with the same label.
